FROM public.ecr.aws/lambda/python:3.13@sha256:31814562fc6d222dd84bf659ae2f0a1bb5ac17b7d217e9c734c7612e326e7559

COPY drivetexas/requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.txt

COPY drivetexas/drivetexas_latest.py ${LAMBDA_TASK_ROOT}/
COPY drivetexas/drivetexas_reaper.py ${LAMBDA_TASK_ROOT}/
COPY drivetexas/.env ${LAMBDA_TASK_ROOT}/.env
COPY shared/ ${LAMBDA_TASK_ROOT}/shared/

ENV HOME="/tmp"

CMD ["drivetexas_latest.handler"]
